update varibles
Updated varibles.

Trying to fix this error:
Fatal error: Class 'Stats3_' not found in single_player.php on line 7
Despite it being declared.